<a href="https://colab.research.google.com/github/Adit2006-bit/portfolio/blob/main/SpendDNA_ADIT_REDDY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SpendDNA - Financial Transaction Analytics

### Name:
# Adit Reddy
### Batch:
June 2026
### Project
Week 2 Minor Project
### Platform
Google Colab
### Dataset
rahul_transactions.csv

This project analyzes six months of financial transaction data of Rahul Sharma.

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", 100)
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
print("Dataset Loaded Successfully")
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])
df.head()

Saving Data set for DADS June.csv to Data set for DADS June (1).csv
Dataset Loaded Successfully
Rows : 1328
Columns : 8

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [ ]:
print("="*60)
print("DATASET OVERVIEW")
print("="*60)
print("\nShape")
print(df.shape)
print("\nColumns")
print(df.columns.tolist())
print("\nMissing Values")
print(df.isnull().sum())
print("\nDuplicate Rows")
print(df.duplicated().sum())
print("\nData Types")
print(df.dtypes)

============================================================
DATASET OVERVIEW
============================================================

Shape
(1328, 8)

Columns
['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref']

Missing Values
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

Duplicate Rows
18

Data Types
Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

In [ ]:
print("Total Unique Descriptions")
print(df["Description"].nunique())
print("\nSample Descriptions\n")
for value in df["Description"].unique()[:50]:
    print(value)

Total Unique Descriptions
283

Sample Descriptions

AMAZON SELLER SVCS
BHIM-BMTC
NEFT-TECHCRUSH LABS-SALARY MAY24
UPI-AMAN-8934@OKAXIS
BHIM-BLINKIT
BHIM ZEPTO
UPI-UBER-2426@HDFCBANK
POS SWIGGY BANGALORE
UPI-GROWWPAY@HDFCBANK
OLA ELECTRIC
BMS MOVIE TICKETS
POS OLA-PRIME
SWIGGY-INSTAMART
UPI-STARBUCKS@AXIS
UPI-THIRDWAVE@OKAXIS
ANI Technologies
BMTC BUS PASS
POS TRUFFLES
FLIPKART INDIA
POS SWIGGY-RESTAURANT
GROFERS INDIA P L
POS UBER BANGALORE
BANGALORE ELEC SUPPLY
TWC INDIA
UPI-BESCOM-BILL@HDFCBANK
UPI-AMAN-0816@OKAXIS
ROPPEN TRANSPORTATION
OLA CABS
POS ZOMATO
UPI-AMAZONPAY@HDFCBANK
POS BLINKIT
IMPS-RENT-LANDLORD-75500265
ZOMATO MEDIA P L
UPI-ANKIT-6430@OKAXIS
UPI-OLACABS@HDFCBANK
UPI-JIORECHARGE@PAYTM
UPI-CCD@HDFCBANK
Swiggy*Order
INSTAMART BANGALORE
UPI-ZOMATO-LIMITED@PAYTM
AVENUE SUPERMARTS
POS HP PETROL STATION
UPI-VIKAS-6060@OKAXIS
POS BANGALORE RESTAURANT
UPI-ZERODHA-COIN@AXIS
BHIM SWIGGY
UPI-BOOKMYSHOW@HDFCBANK
BLINKIT BANGALORE
POS ZEPTO BANGALORE
UPI-DMART@OKAXIS

In [ ]:
REPORT_WIDTH = 70
MONTH_NAMES = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June"
}
print("Project Constants Initialized")

Project Constants Initialized

In [ ]:
# Feature 1
# AI-assisted: Created a working copy of the original dataset
df_clean = df.copy()
print("Working copy created successfully.")
# Parse all mixed date formats
def parse_date(date_value):
    try:
        return pd.to_datetime(date_value, format="mixed", dayfirst=True)
    except:
        return pd.NaT
df_clean["Date"] = df_clean["Date"].apply(parse_date)
invalid_dates = df_clean["Date"].isna().sum()
print("Date parsing completed.")
print("Unparseable dates:", invalid_dates)
# Clean Amount column
df_clean["Amount"] = (
    df_clean["Amount"]
        .astype(str)
        .str.replace("₹", "", regex=False)
        .str.replace("Rs.", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
)
df_clean["Amount"] = pd.to_numeric(
    df_clean["Amount"],
    errors="coerce"
)
invalid_amounts = df_clean["Amount"].isna().sum()
print("Amount parsing completed.")
print("Unparseable amounts:", invalid_amounts)
# Standardize transaction type
df_clean["Type"] = (
    df_clean["Type"]
        .astype(str)
        .str.strip()
        .str.lower()
)
type_mapping = {
    "dr": "debit",
    "debit": "debit",
    "cr": "credit",
    "credit": "credit"
}
df_clean["Type"] = df_clean["Type"].map(type_mapping)
print("Transaction types standardized.\n")
print(df_clean["Type"].value_counts())
# Treat blank Mode values as missing
df_clean["Mode"] = (
    df_clean["Mode"]
        .replace("", np.nan)
)
print("Missing Mode values:", df_clean["Mode"].isna().sum())
# Remove duplicate transactions
rows_before = len(df_clean)
df_clean = df_clean.drop_duplicates()
rows_after = len(df_clean)
duplicates_removed = rows_before - rows_after
print("Duplicate rows removed:", duplicates_removed)
#AI Assisted Remove rows with invalid dates or amounts
rows_before = len(df_clean)
df_clean = df_clean.dropna(subset=["Date", "Amount"])
rows_after = len(df_clean)
removed_rows = rows_before - rows_after
print("Rows removed due to invalid Date/Amount:", removed_rows)
print("=" * 70)
print("FEATURE 1 VALIDATION")
print("=" * 70)
print(f"Original Transactions : {len(df)}")
print(f"Clean Transactions    : {len(df_clean)}")
print(f"Duplicates Removed    : {duplicates_removed}")
print(f"Date Parsing Errors   : {invalid_dates}")
print(f"Amount Parsing Errors : {invalid_amounts}")
print("\nTransaction Types")
print(df_clean["Type"].value_counts())
print("\nMissing Values")
print(df_clean.isnull().sum())
print("\nFeature 1 completed ")

Working copy created successfully.
Date parsing completed.
Unparseable dates: 0
Amount parsing completed.
Unparseable amounts: 0
Transaction types standardized.

Type
debit     1322
credit       6
Name: count, dtype: int64
Missing Mode values: 0
Duplicate rows removed: 18
Rows removed due to invalid Date/Amount: 0
======================================================================
FEATURE 1 VALIDATION
======================================================================
Original Transactions : 1328
Clean Transactions    : 1310
Duplicates Removed    : 18
Date Parsing Errors   : 0
Amount Parsing Errors : 0

Transaction Types
Type
debit     1304
credit       6
Name: count, dtype: int64

Missing Values
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

Feature 1 completed

In [ ]:
# Feature 2
print("=" * 70)
print("FEATURE 2 - VENDOR EXTRACTION")
print("=" * 70)
print("Unique Transaction Descriptions :", df_clean["Description"].nunique())
print("\nSample Descriptions\n")
for desc in sorted(df_clean["Description"].unique())[:100]:
    print(desc)
vendor_keywords = {
    # Food Delivery
    "Swiggy": ["SWIGGY", "BUNDL"],
    "Zomato": ["ZOMATO"],
    # Quick Commerce
    "Blinkit": ["BLINKIT", "GROFERS"],
    "Zepto": ["ZEPTO"],
    "Instamart": ["INSTAMART"],
    # Grocery
    "BigBasket": ["BIGBASKET", "KIRANAKART"],
    "DMart": ["DMART", "AVENUE SUPERMARTS", "INNOVATIVE RETAIL"],
    # Shopping
    "Amazon": ["AMAZON", "AMZN"],
    "Flipkart": ["FLIPKART", "FKART"],
    "Myntra": ["MYNTRA"],
    "Nykaa": ["NYKAA", "FSN"],
    "Ajio": ["AJIO"],
    # Entertainment
    "Netflix": ["NETFLIX"],
    "Spotify": ["SPOTIFY"],
    "Hotstar": ["HOTSTAR", "DISNEY", "STAR INDIA"],
    "BookMyShow": ["BOOKMYSHOW", "BIGTREE", "BMS"],
    # Investments
    "Groww": ["GROWW", "NEXTBILLION"],
    "Zerodha": ["ZERODHA"],
    # Transport
    "Uber": ["UBER"],
    "Ola": ["OLA", "ANI TECHNOLOGIES"],
    "Rapido": ["RAPIDO", "ROPPEN"],
    "BMTC": ["BMTC"],
    # Fuel
    "Indian Oil": ["INDIAN OIL", "IOC"],
    "HP Petrol": ["HP PETROL", "HPCL"],
    "BPCL": ["BPCL"],
    # Utilities
    "Airtel": ["AIRTEL", "BHARTI"],
    "Jio": ["JIO", "JIOFIBER"],
    "BESCOM": ["BESCOM", "BANGALORE ELEC"],
    "BWSSB": ["BWSSB"],
    "Vi": ["VI POSTPAID", "VODAFONE IDEA", "VI-RECHARGE"],
    # Cafes
    "Starbucks": ["STARBUCKS"],
    "Cafe Coffee Day": ["COFFEE DAY", "CCD"],
    "Third Wave Coffee": ["THIRD WAVE", "THIRDWAVE", "TWC INDIA"],
    # Restaurants
    "Empire Restaurant": ["EMPIRE"],
    "Meghana Foods": ["MEGHANA"],
    "Truffles": ["TRUFFLES"],
    "Restaurant": ["RESTAURANT"],
    "Dineout": ["DINEOUT"],
    # Income
    "Salary": ["SALARY", "TECHCRUSH"],
    # Rent
    "Rent": ["LANDLORD", "RENT"],
    # Cash
    "Cash Withdrawal": ["ATM-WDL", "ATM", "WDL"]
}
def extract_vendor(description):
    text = str(description).upper().strip()
    for vendor, keywords in vendor_keywords.items():
        for keyword in keywords:
            if keyword in text:
                return vendor
    if text.startswith("UPI-"):
        if "IOC" in text:
            return "Indian Oil"
        if "THIRDWAVE" in text:
            return "Third Wave Coffee"
        if "RESTAURANT" in text:
            return "Restaurant"
        if "VI" in text:
            return "Vi"
        return "Personal Transfer"
    return "Uncategorised"
if "vendor_clean" in df_clean.columns:
    df_clean.drop(columns=["vendor_clean"], inplace=True)
df_clean["vendor_clean"] = df_clean["Description"].astype(str).apply(extract_vendor)
print("Vendor extraction completed.")
print("="*70)
print("FEATURE 2 VALIDATION")
print("="*70)
print("Unique Canonical Vendors :", df_clean["vendor_clean"].nunique())
print("\nTop 20 Vendors\n")
print(df_clean["vendor_clean"].value_counts().head(20))
uncategorised = df_clean[df_clean["vendor_clean"]=="Uncategorised"]
print("="*70)
print("UNCATEGORISED AUDIT")
print("="*70)
print("Total Uncategorized :", len(uncategorised))
if len(uncategorised):
    print("\nDescriptions\n")
    for d in sorted(uncategorised["Description"].unique()):
        print(d)
else:
    print("No Uncategorized Vendors")

======================================================================
FEATURE 2 - VENDOR EXTRACTION
======================================================================
Unique Transaction Descriptions : 283

Sample Descriptions

AIRTEL POSTPAID
AMAZON IN
AMAZON PRIME VIDEO
AMAZON SELLER SVCS
AMAZONIN MARKETPLACE
AMZN PRIME
AMZN-INTPYMT
ANI Technologies
ATM-WDL-HDFC-3609
ATM-WDL-HDFC-4942
ATM-WDL-HDFC-8030
ATM-WDL-HDFC-8253
ATM-WDL-HDFC-9140
ATM-WDL-ICICI-3918
ATM-WDL-ICICI-4172
ATM-WDL-ICICI-4739
ATM-WDL-ICICI-5025
ATM-WDL-ICICI-6478
ATM-WDL-ICICI-9135
ATM-WDL-SBI-0237
ATM-WDL-SBI-0279
ATM-WDL-SBI-0874
ATM-WDL-SBI-4080
ATM-WDL-SBI-4084
ATM-WDL-SBI-5715
AVENUE SUPERMARTS
Amazon Pay India
BANGALORE ELEC SUPPLY
BESCOM ELEC BILL
BHARTI AIRTEL LTD
BHIM SWIGGY
BHIM ZEPTO
BHIM-BLINKIT
BHIM-BMTC
BIGBASKET BANGALORE
BIGTREE ENTERTAINMENT
BLINKIT BANGALORE
BMS MOVIE TICKETS
BMTC BUS PASS
BUNDL TECH-INSTAMART
BUNDL Tech P L
BWSSB WATER BILL
COFFEE DAY GLOBAL
DISNEY HOTSTAR
FKART INTRNET
FLIPKART INDIA
FSN E-COMMERCE
Flipkart Internet
GROFERS INDIA P L
GROWW INVEST TECH
IMPS ZERODHA-COIN
IMPS-RENT-LANDLORD-35126704
IMPS-RENT-LANDLORD-36852906
IMPS-RENT-LANDLORD-39598076
IMPS-RENT-LANDLORD-49966195
IMPS-RENT-LANDLORD-51148088
IMPS-RENT-LANDLORD-75500265
INNOVATIVE RETAIL
INSTAMART BANGALORE
JIOFIBER
KIRANAKART TECH
MYNTRA DESIGNS
MYNTRA-ORDER
NEFT ZERODHA BROKING
NEFT-TECHCRUSH LABS-SALARY MAY24
NETFLIX ENTERTAINMENT
NETFLIX.COM
NEXTBILLION-GROWW
NYKAA E-RETAIL
OLA CABS
OLA ELECTRIC
POS BANGALORE RESTAURANT
POS BLINKIT
POS BPCL PETROL PUMP
POS CAFE COFFEE DAY
POS DINEOUT
POS DMART BANGALORE
POS EMPIRE RESTAURANT
POS FLIPKART BANGALORE
POS HP PETROL STATION
POS INDIAN OIL BANGALORE
POS INSTAMART
POS MEGHANA FOODS
POS MYNTRA
POS NYKAA BANGALORE
POS OLA-PRIME
POS STARBUCKS BANGALORE
POS SWIGGY BANGALORE
POS SWIGGY-RESTAURANT
POS THIRD WAVE COFFEE
POS TRUFFLES
POS UBER BANGALORE
POS ZEPTO BANGALORE
POS ZOMATO
RAPIDO BIKE TAXI
RELIANCE JIO
ROPPEN TRANSPORTATION
SPOTIFY INDIA
SPOTIFY*PREMIUM
STAR INDIA PVT LTD
Vendor extraction completed.
======================================================================
FEATURE 2 VALIDATION
======================================================================
Unique Canonical Vendors : 41

Top 20 Vendors

vendor_clean
Swiggy               223
Zomato               121
Ola                   87
Amazon                86
Uber                  71
Zepto                 58
Rapido                55
Blinkit               55
Flipkart              47
Starbucks             42
BMTC                  37
Third Wave Coffee     31
DMart                 30
Restaurant            29
Cafe Coffee Day       26
BigBasket             24
Instamart             20
Myntra                20
Nykaa                 19
Cash Withdrawal       17
Name: count, dtype: int64
======================================================================
UNCATEGORISED AUDIT
======================================================================
Total Uncategorized : 0
No Uncategorized Vendors

In [ ]:

# FEATURE 3
#AI Assisted
category_mapping = {
    "Swiggy": "Food",
    "Zomato": "Food",
    "Restaurant": "Food",
    "Empire Restaurant": "Food",
    "Meghana Foods": "Food",
    "Truffles": "Food",
    "Dineout": "Food",
    "Blinkit": "Groceries",
    "Zepto": "Groceries",
    "Instamart": "Groceries",
    "BigBasket": "Groceries",
    "DMart": "Groceries",
    "Amazon": "Shopping",
    "Flipkart": "Shopping",
    "Myntra": "Shopping",
    "Nykaa": "Shopping",
    "Ajio": "Shopping",
    "Netflix": "Entertainment",
    "Spotify": "Entertainment",
    "Hotstar": "Entertainment",
    "BookMyShow": "Entertainment",
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "BMTC": "Transport",
    "Indian Oil": "Fuel",
    "HP Petrol": "Fuel",
    "BPCL": "Fuel",
    "Airtel": "Bills",
    "Jio": "Bills",
    "Vi": "Bills",
    "BESCOM": "Bills",
    "BWSSB": "Bills",
    "Starbucks": "Cafe",
    "Cafe Coffee Day": "Cafe",
    "Third Wave Coffee": "Cafe",
    "Groww": "Investment",
    "Zerodha": "Investment",
    "Salary": "Income",
    "Rent": "Housing",
    "Cash Withdrawal": "Cash",
    "Personal Transfer": "Transfer"
}
def assign_category(vendor):
    return category_mapping.get(vendor, "Others")
    # Remove old category column if it exists
if "category" in df_clean.columns:
    df_clean.drop(columns=["category"], inplace=True)
# Create new category column
df_clean["category"] = df_clean["vendor_clean"].apply(assign_category)
print("Category column created .")
print(df_clean.columns.tolist())
assert "category" in df_clean.columns, "Category column not created!"
print(df_clean[["vendor_clean", "category"]].head())
print("=" * 70)
print("FEATURE 3 VALIDATION")
print("=" * 70)
print("Unique Categories :", df_clean["category"].nunique())
print("\nCategory Distribution\n")
print(df_clean["category"].value_counts())
print("\nSample Records\n")
display(
    df_clean[
        ["Description", "vendor_clean", "category", "Amount"]
    ].head(10)
)

Category column created .
['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'vendor_clean', 'category']
        vendor_clean   category
0             Amazon   Shopping
1               BMTC  Transport
2             Salary     Income
3  Personal Transfer   Transfer
4            Blinkit  Groceries
======================================================================
FEATURE 3 VALIDATION
======================================================================
Unique Categories : 13

Category Distribution

category
Food             417
Transport        250
Groceries        187
Shopping         172
Cafe              99
Bills             47
Entertainment     44
Fuel              28
Investment        23
Cash              17
Transfer          14
Income             6
Housing            6
Name: count, dtype: int64

Sample Records

                        Description       vendor_clean    category   Amount
0                AMAZON SELLER SVCS             Amazon    Shopping   2462.0
1                         BHIM-BMTC               BMTC   Transport     50.0
2  NEFT-TECHCRUSH LABS-SALARY MAY24             Salary      Income  84728.0
3              UPI-AMAN-8934@OKAXIS  Personal Transfer    Transfer   1828.0
4                      BHIM-BLINKIT            Blinkit   Groceries    270.0
5                        BHIM ZEPTO              Zepto   Groceries    625.0
6            UPI-UBER-2426@HDFCBANK               Uber   Transport    148.0
7                      BHIM-BLINKIT            Blinkit   Groceries    482.0
8              POS SWIGGY BANGALORE             Swiggy        Food    537.0
9             UPI-GROWWPAY@HDFCBANK              Groww  Investment   3956.0

In [ ]:
# Feature 4
df_clean["Month"] = df_clean["Date"].dt.to_period("M").astype(str)
print("Month column created.")
# Separate income and expenses
monthly_income = (
    df_clean[df_clean["Type"] == "credit"]
    .groupby("Month")["Amount"]
    .sum()
)
monthly_expense = (
    df_clean[df_clean["Type"] == "debit"]
    .groupby("Month")["Amount"]
    .sum()
)
monthly_summary = (
    pd.DataFrame({
        "Income": monthly_income,
        "Expense": monthly_expense
    })
    .fillna(0)
)
monthly_summary["Savings"] = (
    monthly_summary["Income"] - monthly_summary["Expense"]
)
monthly_summary = monthly_summary.round(2)
print("Monthly summary created.")
category_monthly = (
    df_clean[df_clean["Type"] == "debit"]
    .pivot_table(
        values="Amount",
        index="Month",
        columns="category",
        aggfunc="sum",
        fill_value=0
    )
    .round(2)
)
print("Category-wise monthly expense table created.")
top_vendors = (
    df_clean[df_clean["Type"] == "debit"]
    .groupby("vendor_clean")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .round(2)
)
print("Top vendors calculated.")
print("=" * 70)
print("FEATURE 4 - MONTHLY ANALYTICS")
print("=" * 70)
print(f"Total Transactions : {len(df_clean)}")
print(f"Total Debit Amount : ₹{df_clean[df_clean['Type']=='debit']['Amount'].sum():,.2f}")
print(f"Total Credit Amount : ₹{df_clean[df_clean['Type']=='credit']['Amount'].sum():,.2f}")
print(f"Average Debit : ₹{df_clean[df_clean['Type']=='debit']['Amount'].mean():,.2f}")
print(f"Average Credit : ₹{df_clean[df_clean['Type']=='credit']['Amount'].mean():,.2f}")
print("=" * 70)
print("MONTHLY INCOME VS EXPENSE")
print("=" * 70)
display(monthly_summary)
print("=" * 70)
print("CATEGORY-WISE MONTHLY EXPENSE")
print("=" * 70)
display(category_monthly)
print("=" * 70)
print("TOP 10 VENDORS BY SPENDING")
print("=" * 70)
display(top_vendors)

Month column created.
Monthly summary created.
Category-wise monthly expense table created.
Top vendors calculated.
======================================================================
FEATURE 4 - MONTHLY ANALYTICS
======================================================================
Total Transactions : 1310
Total Debit Amount : ₹1,678,901.00
Total Credit Amount : ₹509,774.00
Average Debit : ₹1,287.50
Average Credit : ₹84,962.33
======================================================================
MONTHLY INCOME VS EXPENSE
======================================================================

          Income   Expense   Savings
Month
2024-01  84728.0  290767.0 -206039.0
2024-02  84724.0  234071.0 -149347.0
2024-03  84701.0  330458.0 -245757.0
2024-04  84736.0  251382.0 -166646.0
2024-05  85393.0  277306.0 -191913.0
2024-06  85492.0  294917.0 -209425.0

======================================================================
CATEGORY-WISE MONTHLY EXPENSE
======================================================================

category,Bills,Cafe,Cash,Entertainment,Food,Fuel,Groceries,Housing,Investment,Shopping,Transfer,Transport
Month,,,,,,,,,,,,
2024-01,9486.0,3690.0,2000.0,4030.0,38953.0,30322.0,28703.0,18000.0,38432.0,98623.0,7523.0,11005.0
2024-02,6870.0,4273.0,5000.0,5102.0,45512.0,2079.0,23748.0,18000.0,15000.0,94011.0,4285.0,10191.0
2024-03,7357.0,5448.0,8000.0,5927.0,53116.0,26164.0,20315.0,18000.0,68644.0,108215.0,2415.0,6857.0
2024-04,5831.0,6564.0,5500.0,4392.0,35467.0,18718.0,23618.0,18000.0,54126.0,69219.0,663.0,9284.0
2024-05,4340.0,5668.0,8000.0,1844.0,47694.0,9138.0,21665.0,18000.0,48628.0,95776.0,3412.0,13141.0
2024-06,12790.0,5802.0,17000.0,5469.0,47834.0,2882.0,15240.0,18000.0,23330.0,138033.0,1541.0,6996.0

======================================================================
TOP 10 VENDORS BY SPENDING
======================================================================

vendor_clean
Amazon             328530.0
Zerodha            210000.0
Flipkart           177510.0
Rent               108000.0
Swiggy              95523.0
Myntra              69529.0
Indian Oil          56335.0
Zomato              55316.0
DMart               46662.0
Cash Withdrawal     45500.0
Name: Amount, dtype: float64

In [ ]:
# FEATURE 5
monthly_trend = (
    df_clean[df_clean["Type"] == "debit"]
    .groupby("Month")["Amount"]
    .agg(
        Total_Spending="sum",
        Transactions="count",
        Average_Spending="mean"
    )
    .round(2)
)
print("Monthly trend created successfully.")
monthly_category = (
    df_clean[df_clean["Type"] == "debit"]
    .pivot_table(
        index="Month",
        columns="category",
        values="Amount",
        aggfunc="sum",
        fill_value=0
    )
    .round(2)
)
print("Monthly category trend created.")
monthly_trend["Previous_Month"] = monthly_trend["Total_Spending"].shift(1)
# AI Assisted
monthly_trend["Change"] = (
    monthly_trend["Total_Spending"] -
    monthly_trend["Previous_Month"]
).round(2)
monthly_trend["Trend"] = monthly_trend["Change"].apply(
    lambda x: "Increase" if x > 0 else ("Decrease" if x < 0 else "No Change")
)
monthly_trend = monthly_trend.fillna("-")
print("=" * 70)
print("FEATURE 5 - MONTHLY TRENDS")
print("=" * 70)
display(monthly_trend)
print("\nCATEGORY-WISE MONTHLY TREND\n")
display(monthly_category)
print("=" * 70)
print("FEATURE 5 VALIDATION")
print("=" * 70)
print("Months Analysed :", monthly_trend.shape[0])
print("Trend Direction\n")
print(monthly_trend[["Total_Spending", "Trend"]])

Monthly trend created successfully.
Monthly category trend created.
======================================================================
FEATURE 5 - MONTHLY TRENDS
======================================================================

,Total_Spending,Transactions,Average_Spending,Previous_Month,Change,Trend
Month,,,,,,
2024-01,290767.0,218,1333.79,-,-,No Change
2024-02,234071.0,212,1104.11,290767.0,-56696.0,Decrease
2024-03,330458.0,216,1529.90,234071.0,96387.0,Increase
2024-04,251382.0,221,1137.48,330458.0,-79076.0,Decrease
2024-05,277306.0,223,1243.52,251382.0,25924.0,Increase
2024-06,294917.0,214,1378.12,277306.0,17611.0,Increase

CATEGORY-WISE MONTHLY TREND

category,Bills,Cafe,Cash,Entertainment,Food,Fuel,Groceries,Housing,Investment,Shopping,Transfer,Transport
Month,,,,,,,,,,,,
2024-01,9486.0,3690.0,2000.0,4030.0,38953.0,30322.0,28703.0,18000.0,38432.0,98623.0,7523.0,11005.0
2024-02,6870.0,4273.0,5000.0,5102.0,45512.0,2079.0,23748.0,18000.0,15000.0,94011.0,4285.0,10191.0
2024-03,7357.0,5448.0,8000.0,5927.0,53116.0,26164.0,20315.0,18000.0,68644.0,108215.0,2415.0,6857.0
2024-04,5831.0,6564.0,5500.0,4392.0,35467.0,18718.0,23618.0,18000.0,54126.0,69219.0,663.0,9284.0
2024-05,4340.0,5668.0,8000.0,1844.0,47694.0,9138.0,21665.0,18000.0,48628.0,95776.0,3412.0,13141.0
2024-06,12790.0,5802.0,17000.0,5469.0,47834.0,2882.0,15240.0,18000.0,23330.0,138033.0,1541.0,6996.0

======================================================================
FEATURE 5 VALIDATION
======================================================================
Months Analysed : 6
Trend Direction

         Total_Spending      Trend
Month
2024-01        290767.0  No Change
2024-02        234071.0   Decrease
2024-03        330458.0   Increase
2024-04        251382.0   Decrease
2024-05        277306.0   Increase
2024-06        294917.0   Increase

In [ ]:
# FEATURE 6
#AI Assisted
def get_time_bucket(time_str):
    hour = int(str(time_str).split(":")[0])
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"
df_clean["Time_Bucket"] = df_clean["Time"].apply(get_time_bucket)
print("Time buckets created.")
time_summary = (
    df_clean
    .groupby("Time_Bucket")
    .size()
    .rename("Transactions")
    .to_frame()
)
print(time_summary)
time_analysis = (
    df_clean
    .groupby(["Time_Bucket","Type"])["Amount"]
    .agg(["count","sum","mean"])
    .round(2)
)
display(time_analysis)
busiest = (
    df_clean["Time_Bucket"]
    .value_counts()
)
print("="*60)
print("FEATURE 5 ANALYSIS")
print("="*60)
print("Busiest Time Bucket :", busiest.idxmax())
print("Transactions        :", busiest.max())
category_time = (
    pd.crosstab(
        df_clean["Time_Bucket"],
        df_clean["category"]
    )
)
display(category_time)
print("="*60)
print("VALIDATION")
print("="*60)
print("Total Transactions :", len(df_clean))
print("Bucket Total       :", time_summary["Transactions"].sum())

Time buckets created.
             Transactions
Time_Bucket
Afternoon             314
Evening               340
Morning               354
Night                 302

                    count       sum      mean
Time_Bucket Type
Afternoon   debit     314  452169.0   1440.03
Evening     debit     340  363884.0   1070.25
Morning     credit      6  509774.0  84962.33
            debit     348  501130.0   1440.03
Night       debit     302  361718.0   1197.74

============================================================
FEATURE 5 ANALYSIS
============================================================
Busiest Time Bucket : Morning
Transactions        : 354

category,Bills,Cafe,Cash,Entertainment,Food,Fuel,Groceries,Housing,Income,Investment,Shopping,Transfer,Transport
Time_Bucket,,,,,,,,,,,,,
Afternoon,14,28,3,5,98,10,45,4,0,1,34,5,67
Evening,9,24,2,6,151,4,45,0,0,3,27,5,64
Morning,12,38,9,12,72,6,47,2,6,12,52,1,85
Night,12,9,3,21,96,8,50,0,0,7,59,3,34

============================================================
VALIDATION
============================================================
Total Transactions : 1310
Bucket Total       : 1310

In [ ]:
# FEATURE 7

debit_df = df_clean[df_clean["Type"] == "debit"].copy()
mean_amount = debit_df["Amount"].mean()
std_amount = debit_df["Amount"].std()
debit_df["Z_Score"] = (
    (debit_df["Amount"] - mean_amount)
    / std_amount
)
print("Z-score calculated.")
anomalies = debit_df[
    debit_df["Z_Score"].abs() >= 3
].copy()
print("Anomaly detection completed.")
anomalies = anomalies.sort_values(
    by="Amount",
    ascending=False
)
print("=" * 70)
print("FEATURE 7 - TOP ANOMALIES")
print("=" * 70)
display(
    anomalies[
        [
            "Date",
            "Time",
            "Description",
            "vendor_clean",
            "category",
            "Amount",
            "Z_Score"
        ]
    ].head(20)
)
#AI Assisted
print("=" * 70)
print("ANOMALY SUMMARY")
print("=" * 70)
print("Mean Amount        : ₹{:.2f}".format(mean_amount))
print("Standard Deviation : ₹{:.2f}".format(std_amount))
print()
print("Total Debit Transactions :", len(debit_df))
print("Total Anomalies          :", len(anomalies))
vendor_anomaly = (
    anomalies
    .groupby("vendor_clean")
    .agg(
        Transactions=("Amount", "count"),
        Total_Amount=("Amount", "sum")
    )
    .sort_values(
        by="Total_Amount",
        ascending=False
    )
)
print("=" * 70)
print("ANOMALOUS VENDORS")
print("=" * 70)
display(vendor_anomaly)
print("=" * 70)
print("FEATURE 7 VALIDATION")
print("=" * 70)
print("Formula Used")
print("Z = (Amount - Mean) / Standard Deviation")
print()
print("Maximum Z-Score :", round(debit_df["Z_Score"].max(), 2))
print("Minimum Z-Score :", round(debit_df["Z_Score"].min(), 2))
print()
print("Top 10 Largest Transactions")
display(
    debit_df.nlargest(
        10,
        "Amount"
    )[
        [
            "Description",
            "vendor_clean",
            "Amount",
            "Z_Score"
        ]
    ]
)

Z-score calculated.
Anomaly detection completed.
======================================================================
FEATURE 7 - TOP ANOMALIES
======================================================================

,Date,Time,Description,vendor_clean,category,Amount,Z_Score
1298,2024-06-26,09:07,AMAZONIN MARKETPLACE,Amazon,Shopping,22008.0,7.390683
269,2024-02-07,17:28,UPI-AMAZONPAY@HDFCBANK,Amazon,Shopping,21986.0,7.382836
475,2024-03-05,21:33,UPI-AMAZONPAY@HDFCBANK,Amazon,Shopping,19917.0,6.644856
450,2024-03-02,11:58,AMAZON IN,Amazon,Shopping,18273.0,6.058466
456,2024-03-03,13:12,IMPS-RENT-LANDLORD-51148088,Rent,Housing,18000.0,5.961092
34,2024-01-05,11:43,IMPS-RENT-LANDLORD-75500265,Rent,Housing,18000.0,5.961092
248,2024-02-05,11:24,IMPS-RENT-LANDLORD-39598076,Rent,Housing,18000.0,5.961092
913,2024-05-05,13:23,IMPS-RENT-LANDLORD-49966195,Rent,Housing,18000.0,5.961092
695,2024-04-05,13:45,IMPS-RENT-LANDLORD-36852906,Rent,Housing,18000.0,5.961092
1128,2024-06-03,14:21,IMPS-RENT-LANDLORD-35126704,Rent,Housing,18000.0,5.961092
1079,2024-05-27,14:46,UPI-FLIPKART@HDFCBANK,Flipkart,Shopping,17831.0,5.900812
1291,2024-06-25,14:21,Amazon Pay India,Amazon,Shopping,17504.0,5.784176
1130,2024-06-03,16:09,UPI-FLIPKART@HDFCBANK,Flipkart,Shopping,16369.0,5.379339
169,2024-01-24,18:43,FLIPKART INDIA,Flipkart,Shopping,16260.0,5.340460
1308,2024-06-27,16:33,FLIPKART INDIA,Flipkart,Shopping,15955.0,5.231671
651,2024-03-31,13:24,AMAZONIN MARKETPLACE,Amazon,Shopping,15953.0,5.230958
1041,2024-05-22,20:20,ZERODHA SECURITIES,Zerodha,Investment,15000.0,4.891038
1010,2024-05-18,18:20,UPI-ZERODHA-COIN@AXIS,Zerodha,Investment,15000.0,4.891038
129,2024-01-19,22:56,NEFT ZERODHA BROKING,Zerodha,Investment,15000.0,4.891038
50,2024-01-07,10:24,UPI-ZERODHA-COIN@AXIS,Zerodha,Investment,15000.0,4.891038

======================================================================
ANOMALY SUMMARY
======================================================================
Mean Amount        : ₹1287.50
Standard Deviation : ₹2803.60

Total Debit Transactions : 1304
Total Anomalies          : 40
======================================================================
ANOMALOUS VENDORS
======================================================================

              Transactions  Total_Amount
vendor_clean
Zerodha                 14      210000.0
Amazon                   9      159075.0
Rent                     6      108000.0
Flipkart                 6       95136.0
Myntra                   3       33701.0
Indian Oil               2       20913.0

======================================================================
FEATURE 7 VALIDATION
======================================================================
Formula Used
Z = (Amount - Mean) / Standard Deviation

Maximum Z-Score : 7.39
Minimum Z-Score : -0.46

Top 10 Largest Transactions

                      Description vendor_clean   Amount   Z_Score
1298         AMAZONIN MARKETPLACE       Amazon  22008.0  7.390683
269        UPI-AMAZONPAY@HDFCBANK       Amazon  21986.0  7.382836
475        UPI-AMAZONPAY@HDFCBANK       Amazon  19917.0  6.644856
450                     AMAZON IN       Amazon  18273.0  6.058466
34    IMPS-RENT-LANDLORD-75500265         Rent  18000.0  5.961092
248   IMPS-RENT-LANDLORD-39598076         Rent  18000.0  5.961092
456   IMPS-RENT-LANDLORD-51148088         Rent  18000.0  5.961092
695   IMPS-RENT-LANDLORD-36852906         Rent  18000.0  5.961092
913   IMPS-RENT-LANDLORD-49966195         Rent  18000.0  5.961092
1128  IMPS-RENT-LANDLORD-35126704         Rent  18000.0  5.961092

In [ ]:
# FEATURE 8
if "Hour" not in df_clean.columns:
    df_clean["Hour"] = (
        df_clean["Time"]
        .astype(str)
        .str.split(":")
        .str[0]
        .astype(int)
    )
profile = {}
profile["food_spend"] = df_clean[df_clean["category"]=="Food"]["Amount"].sum()
profile["shopping_spend"] = df_clean[df_clean["category"]=="Shopping"]["Amount"].sum()
profile["investment_spend"] = df_clean[df_clean["category"]=="Investment"]["Amount"].sum()
profile["transport_spend"] = df_clean[df_clean["category"]=="Transport"]["Amount"].sum()
profile["cafe_spend"] = df_clean[df_clean["category"]=="Cafe"]["Amount"].sum()
profile["bill_spend"] = df_clean[df_clean["category"]=="Bills"]["Amount"].sum()
profile["late_night_orders"] = len(
    df_clean[
        (df_clean["Hour"]>=21) &
        (df_clean["vendor_clean"].isin(["Swiggy","Zomato"]))
    ]
)
profile["amazon_orders"] = len(df_clean[df_clean["vendor_clean"]=="Amazon"])
profile["swiggy_orders"] = len(df_clean[df_clean["vendor_clean"]=="Swiggy"])
profile["zomato_orders"] = len(df_clean[df_clean["vendor_clean"]=="Zomato"])
print(profile)
def foodie(profile):
    return profile["food_spend"] > 70000
def investor(profile):
    return profile["investment_spend"] > 100000
def shopaholic(profile):
    return profile["shopping_spend"] > 150000
def commuter(profile):
    return profile["transport_spend"] > 40000
def cafe_lover(profile):
    return profile["cafe_spend"] > 20000
def night_owl(profile):
    return profile["late_night_orders"] >= 10
archetypes = []
if foodie(profile):
    archetypes.append("Foodie")
if investor(profile):
    archetypes.append("Investor")
if shopaholic(profile):
    archetypes.append("Shopaholic")
if commuter(profile):
    archetypes.append("Daily Commuter")
if cafe_lover(profile):
    archetypes.append("Cafe Lover")
if night_owl(profile):
    archetypes.append("Night Owl")
    print("="*70)
print("FEATURE 8 - ARCHETYPE DETECTION")
print("="*70)
print("Detected Archetypes\n")
for i, archetype in enumerate(archetypes,1):
    print(f"{i}. {archetype}")
    print("\n"+"="*70)
print("SUPPORTING METRICS")
print("="*70)
print(f"Food Spend           : ₹{profile['food_spend']:,.2f}")
print(f"Shopping Spend       : ₹{profile['shopping_spend']:,.2f}")
print(f"Investment Spend     : ₹{profile['investment_spend']:,.2f}")
print(f"Transport Spend      : ₹{profile['transport_spend']:,.2f}")
print(f"Cafe Spend           : ₹{profile['cafe_spend']:,.2f}")
print(f"Bills                : ₹{profile['bill_spend']:,.2f}")
print()
print(f"Amazon Orders        : {profile['amazon_orders']}")
print(f"Swiggy Orders        : {profile['swiggy_orders']}")
print(f"Zomato Orders        : {profile['zomato_orders']}")
print(f"Late Night Orders    : {profile['late_night_orders']}")
print("="*70)
print("FEATURE 8 VALIDATION")
print("="*70)
print("Functions Used")
print("foodie()")
print("investor()")
print("shopaholic()")
print("commuter()")
print(" cafe_lover()")
print("night_owl()")
print()
print("Total Archetypes Detected :", len(archetypes))

{'food_spend': np.float64(268576.0), 'shopping_spend': np.float64(603877.0), 'investment_spend': np.float64(248160.0), 'transport_spend': np.float64(57474.0), 'cafe_spend': np.float64(31445.0), 'bill_spend': np.float64(46674.0), 'late_night_orders': 61, 'amazon_orders': 86, 'swiggy_orders': 223, 'zomato_orders': 121}
======================================================================
FEATURE 8 - ARCHETYPE DETECTION
======================================================================
Detected Archetypes

1. Foodie

======================================================================
2. Investor

======================================================================
3. Shopaholic

======================================================================
4. Daily Commuter

======================================================================
5. Cafe Lover

======================================================================
6. Night Owl

======================================================================
SUPPORTING METRICS
======================================================================
Food Spend           : ₹268,576.00
Shopping Spend       : ₹603,877.00
Investment Spend     : ₹248,160.00
Transport Spend      : ₹57,474.00
Cafe Spend           : ₹31,445.00
Bills                : ₹46,674.00

Amazon Orders        : 86
Swiggy Orders        : 223
Zomato Orders        : 121
Late Night Orders    : 61
======================================================================
FEATURE 8 VALIDATION
======================================================================
Functions Used
foodie()
investor()
shopaholic()
commuter()
 cafe_lover()
night_owl()

Total Archetypes Detected : 6

In [ ]:
# Final Output and Insights
category_total = (
    df_clean[df_clean["Type"] == "debit"]
    .groupby("category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)
print("="*80)
print("        PERSONAL FINANCE ANALYTICS REPORT")
print("="*80)
print(f"Total Transactions        : {len(df_clean)}")
print(f"Total Debit               : ₹{df_clean[df_clean['Type']=='debit']['Amount'].sum():,.2f}")
print(f"Total Credit              : ₹{df_clean[df_clean['Type']=='credit']['Amount'].sum():,.2f}")
print()
print(f"Unique Vendors            : {df_clean['vendor_clean'].nunique()}")
print(f"Expense Categories        : {df_clean['category'].nunique()}")
print()
print(f"Busiest Time of Day       : {time_summary['Transactions'].idxmax()}")
print(f"Top Spending Vendor       : {top_vendors.index[0]}")
print(f"Highest Spending Category : {category_total.idxmax()}")
print()
print(f"Detected Archetypes       : {', '.join(archetypes)}")
print("="*80)
print("="*80)
print("KEY INSIGHTS")
print("="*80)

print("1.")
print(
    f"Shopping is Rahul's largest expense category "
    f"(₹{profile['shopping_spend']:,.0f}), indicating a strong preference "
    "for online retail platforms such as Amazon, Flipkart and Myntra."
)
print()

print("2.")
print(
    f"Rahul placed {profile['late_night_orders']} late-night food orders "
    "through Swiggy and Zomato, suggesting frequent food delivery during night hours."
)
print()
print("3.")
print(
    f"Despite spending ₹{profile['shopping_spend']:,.0f} on shopping, "
    f"Rahul also invested ₹{profile['investment_spend']:,.0f}, "
    "indicating a balance between discretionary spending and long-term financial planning."
)
print("="*80)
print("PROJECT SUMMARY")
print("="*80)

print("""
The project converts raw banking transactions into meaningful financial
insights that help understand customer behaviour and spending patterns.
""")

================================================================================
        PERSONAL FINANCE ANALYTICS REPORT
================================================================================
Total Transactions        : 1310
Total Debit               : ₹1,678,901.00
Total Credit              : ₹509,774.00

Unique Vendors            : 41
Expense Categories        : 13

Busiest Time of Day       : Morning
Top Spending Vendor       : Amazon
Highest Spending Category : Shopping

Detected Archetypes       : Foodie, Investor, Shopaholic, Daily Commuter, Cafe Lover, Night Owl
================================================================================
================================================================================
KEY INSIGHTS
================================================================================
1.
Shopping is Rahul's largest expense category (₹603,877), indicating a strong preference for online retail platforms such as Amazon, Flipkart and Myntra.

2.
Rahul placed 61 late-night food orders through Swiggy and Zomato, suggesting frequent food delivery during night hours.

3.
Despite spending ₹603,877 on shopping, Rahul also invested ₹248,160, indicating a balance between discretionary spending and long-term financial planning.
================================================================================
PROJECT SUMMARY
================================================================================

The project converts raw banking transactions into meaningful financial
insights that help understand customer behaviour and spending patterns.